apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-service
  namespace: recsys-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-service
  template:
    metadata:
      labels:
        app: event-service
    spec:
      containers:
      - name: event-service
        image: nikolayoleynik/event-service:latest
        ports:
        - containerPort: 80
        env:
        - name: KAFKA_BROKER
          value: "my-cluster-kafka-bootstrap.kafka:9092"
---
apiVersion: v1
kind: Service
metadata:
  name: event-service
  namespace: recsys-prod
spec:
  selector:
    app: event-service
  ports:
  - port: 80
    targetPort: 80