apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Nikiti7/System-design.git"
    targetRevision: HEAD
    path: k8s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: recsys-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
